import type { Person } from "@/types/person";

// Seed data ported from the previous static site. Once Supabase is wired up,
// this should be replaced by a query against the `people` table.
export const PEOPLE: Person[] = [
  {
    id: "1",
    name: "Prof. Shubhendu Bhasin",
    image_url: "/Assets/faculty/1.jpg",
    webmail: "sbhasin@ee.iitd.ac.in",
    link: "http://web.iitd.ac.in/~sbhasin/",
    role: "faculty",
    year: null,
    department: "Electrical Engineering",
    department_category: "electrical",
    office_contact: "+911126591124",
    research_interest: "Nonlinear & Adaptive Control, Learning-based Control, Robotics",
    focus: ["nonlinear", "control", "adaptive", "learning", "data", "driven", "robotics", "systems", "ai"],
  },
  {
    id: "2",
    name: "Prof. S.K Saha",
    image_url: "/Assets/faculty/2.jpg",
    webmail: "saha@mech.iitd.ac.in",
    link: "http://www.sksaha.com",
    role: "faculty",
    year: null,
    department: "Mechanical Engineering",
    department_category: "mechanical",
    office_contact: "+911126591135",
    research_interest: "Multibody Dynamics, Robotics, Mechatronics",
    focus: ["multibody", "dynamics", "robotics", "mechanism", "design", "mechatronics", "kinematics", "control"],
  },
  {
    id: "3",
    name: "Prof. Subodh Kumar",
    image_url: "/Assets/faculty/3.jpg",
    webmail: "subodh@cse.iitd.ac.in",
    link: "http://www.cse.iitd.ac.in/~subodh/",
    role: "faculty",
    year: null,
    department: "Computer Science and Engineering",
    department_category: "computer",
    office_contact: "+911126596032",
    research_interest: "Computer Graphics, Medical Visualization, HRI, Teleoperation",
    focus: ["computer", "graphics", "visualization", "medical", "surgical", "simulation", "virtual", "reality", "vr", "rendering", "parallel", "computing", "hri", "human", "robot", "interaction", "teleoperation", "robotics"],
  },
  {
    id: "4",
    name: "Prof. Sunil Jha",
    image_url: "/Assets/faculty/4.jpg",
    webmail: "suniljha@mech.iitd.ac.in",
    link: "https://mech.iitd.ac.in/faculty-profile/169",
    role: "faculty",
    year: null,
    department: "Mechanical Engineering",
    department_category: "mechanical",
    office_contact: "+911126591125",
    research_interest: "Advanced Manufacturing, Micro/Nano Finishing, Robotics & Automation",
    focus: ["manufacturing", "automation", "machining", "finishing", "micro", "nano", "mechatronics", "robotics", "smart", "materials", "mr", "fluids", "magnetorheological", "industrial"],
  },
  {
    id: "5",
    name: "Prof. Chetan Arora",
    image_url: "/Assets/faculty/5.jpg",
    webmail: "chetan@cse.iitd.ac.in",
    link: "http://www.cse.iitd.ac.in/~chetan",
    role: "faculty",
    year: null,
    department: "Computer Science and Engineering",
    department_category: "computer",
    office_contact: "+911126591279",
    research_interest: "Trustworthy AI, Computer Vision, Healthcare AI",
    focus: ["trustworthy", "ai", "artificial", "intelligence", "computer", "vision", "cancer", "detection", "healthcare", "medical", "mobility", "egocentric", "systems", "deep", "learning", "machine"],
  },
  {
    id: "6",
    name: "Prof. Kolin Paul",
    image_url: "/Assets/faculty/6.jpg",
    webmail: "kolin@cse.iitd.ac.in",
    link: "https://kolinpaul.github.io/",
    role: "faculty",
    year: null,
    department: "Computer Science Engineering",
    department_category: "computer",
    office_contact: "+911126596033",
    research_interest: null,
    focus: ["embedded", "systems", "healthcare", "technology", "affordable", "iot", "medical", "devices", "edge", "computing", "ai"],
  },
  {
    id: "7",
    name: "Prof. Sudipto Mukherjee",
    image_url: "/Assets/faculty/7.jpg",
    webmail: "sudipto@mech.iitd.ac.in",
    link: "https://mech.iitd.ac.in/faculty-profile/158",
    role: "faculty",
    year: null,
    department: "Mechanical Engineering",
    department_category: "mechanical",
    office_contact: "+911126591138",
    research_interest: null,
    focus: ["mechanism", "design", "robotics", "mechanical", "systems", "biomechanics", "impact", "dynamics", "kinematics", "robot"],
  },
  {
    id: "8",
    name: "Prof. Husain Kanchwala",
    image_url: "/Assets/faculty/8.png",
    webmail: "husaink@iitd.ac.in",
    link: "https://web.iitd.ac.in/~husaink/",
    role: "faculty",
    year: null,
    department: "Center for Automotive Research and Tribology",
    department_category: "cart",
    office_contact: "+91-11-2654-8571",
    research_interest: null,
    focus: ["vehicle", "dynamics", "control", "autonomous", "vehicles", "vibrations", "system", "modeling", "systems", "automotive", "engineering", "robotics", "mobility"],
  },
  {
    id: "9",
    name: "Prof. I.N. Kar",
    image_url: "/Assets/faculty/9.jpg",
    webmail: "ink@ee.iitd.ac.in",
    link: "http://web.iitd.ac.in/~ink/",
    role: "faculty",
    year: null,
    department: "Electrical Engineering",
    department_category: "electrical",
    office_contact: "+91-11-26591093",
    research_interest: null,
    focus: ["nonlinear", "control", "robotics", "theory", "time", "delay", "systems", "cyber", "physical", "cps", "distributed", "optimization", "robust", "security"],
  },
  {
    id: "10",
    name: "Prof. Jitendra Prasad Khatait",
    image_url: "/Assets/faculty/10.jpg",
    webmail: "jpkhatait@mech.iitd.ac.in",
    link: "http://web.iitd.ac.in/~jpkhatait/",
    role: "faculty",
    year: null,
    department: "Mechanical Engineering",
    department_category: "mechanical",
    office_contact: "+911126591132",
    research_interest: null,
    focus: ["precision", "engineering", "machine", "design", "flexures", "robotics", "medical", "devices", "mechanism", "micro", "systems", "mechanics"],
  },
  {
    id: "11",
    name: "Prof. Sitikantha Roy",
    image_url: "/Assets/faculty/11.jpg",
    webmail: "sroy@am.iitd.ac.in",
    link: "https://sites.google.com/view/sitilab-iitd/",
    role: "faculty",
    year: null,
    department: "Applied Mechanics",
    department_category: "applied",
    office_contact: "+911126591220",
    research_interest: null,
    focus: ["biomechanics", "soft", "robotics", "bioinspired", "engineering", "smart", "materials", "composite", "structures", "control", "systems", "bio", "mechanics"],
  },
  {
    id: "12",
    name: "Prof. Kaushik Mukherjee",
    image_url: "/Assets/faculty/12.png",
    webmail: "kmukherjee@mech.iitd.ac.in",
    link: "https://mech.iitd.ac.in/faculty-profile/192",
    role: "faculty",
    year: null,
    department: "Mechanical Engineering",
    department_category: "mechanical",
    office_contact: "+911126548710",
    research_interest: null,
    focus: ["biomechanics", "orthopaedics", "implant", "design", "mechanobiology", "human", "movement", "finite", "element", "analysis", "fea", "medical", "engineering", "bio", "mechanics"],
  },
  {
    id: "13",
    name: "Prof. Satinder Paul Singh",
    image_url: "/Assets/faculty/13.jpg",
    webmail: "singhsp@mech.iitd.ernet.in",
    link: "http://web.iitd.ac.in/~singhsp/",
    role: "faculty",
    year: null,
    department: "Mechanical Engineering",
    department_category: "mechanical",
    office_contact: "(91)-11-26591136",
    research_interest: null,
    focus: ["machine", "dynamics", "vibration", "control", "composite", "materials", "design", "nano", "mechanics", "structural", "rotating", "machinery"],
  },
  {
    id: "14",
    name: "Prof. Sumantra Dutta Roy",
    image_url: "/Assets/faculty/14.jpg",
    webmail: "sumantra@ee.iitd.ac.in",
    link: "http://www.cse.iitd.ernet.in/~sumantra/",
    role: "faculty",
    year: null,
    department: "Electrical Engineering",
    department_category: "electrical",
    office_contact: "+911126591084",
    research_interest: null,
    focus: ["computer", "vision", "image", "processing", "pattern", "recognition", "machine", "learning", "biometrics", "medical", "informatics", "bioinformatics", "signal", "ai", "deep"],
  },
  {
    id: "15",
    name: "Prof. S Janardhanan",
    image_url: "/Assets/faculty/15.jpg",
    webmail: "janas@ee.iitd.ac.in",
    link: "http://web.iitd.ac.in/~janas/",
    role: "faculty",
    year: null,
    department: "Electrical Engineering",
    department_category: "electrical",
    office_contact: "+911126591091",
    research_interest: null,
    focus: ["control", "systems", "robust", "sliding", "mode", "discrete", "nonlinear", "dynamics", "theory"],
  },
  {
    id: "16",
    name: "Prof. Rohan Paul",
    image_url: "/Assets/faculty/16.jpg",
    webmail: "rohan@cse.iitd.ac.in",
    link: "https://www.cse.iitd.ac.in/~rohanpaul/index.html",
    role: "faculty",
    year: null,
    department: "Computer Science and Engineering",
    department_category: "computer",
    office_contact: "+911126548435",
    research_interest: null,
    focus: ["robotics", "artificial", "intelligence", "assistive", "technology", "human", "robot", "interaction", "hri", "ai", "autonomous", "systems", "healthcare"],
  },
  {
    id: "17",
    name: "Prof. Rama Krishna K",
    image_url: "/Assets/faculty/17.jpg",
    webmail: "rkk@mech.iitd.ac.in",
    link: "https://mech.iitd.ac.in/faculty-profile/190",
    role: "faculty",
    year: null,
    department: "Mechanical Engineering",
    department_category: "mechanical",
    office_contact: "+911126591105",
    research_interest: null,
    focus: ["kinematics", "mechanisms", "machine", "design", "cad", "geometric", "modeling", "manufacturing", "mechanics", "robotics", "mechanism"],
  },
  {
    id: "18",
    name: "Prof. Amber Srivastava",
    image_url: "/Assets/faculty/amber.jpg",
    webmail: "asrvstv@mech.iitd.ac.in",
    link: "https://mech.iitd.ac.in/faculty-profile/203",
    role: "faculty",
    year: null,
    department: "Mechanical Engineering",
    department_category: "mechanical",
    office_contact: "+911126591105",
    research_interest: null,
    focus: ["optimization", "control", "reinforcement-learning", "decision-making", "mdp", "industry-4", "predictive-control", "system-identification"],
  },
  {
    id: "19",
    name: "Prof. Arambam James Singh",
    image_url: "/Assets/faculty/James.png",
    webmail: "jamesa@scai.iitd.ac.in",
    link: "https://jamesarambam.me/",
    role: "faculty",
    year: null,
    department: "School of AI",
    department_category: "scai",
    office_contact: "",
    research_interest: null,
    focus: ["reinforcement-learning", "multi-agent", "systems", "large-scale", "ai"],
  },
  {
    id: "20",
    name: "Prof. Deepak Umakant Patil",
    image_url: "/Assets/faculty/deepak.png",
    webmail: "deepakpatil@ee.iitd.ac.in",
    link: "https://web.iitd.ac.in/~deepakpatil/",
    role: "faculty",
    year: null,
    department: "Electrical Engineering",
    department_category: "electrical",
    office_contact: "+911126591094",
    research_interest: null,
    focus: ["control-theory", "optimization", "multi-agent", "differential-games", "hybrid-systems"],
  },
  {
    id: "21",
    name: "Prof. Raunak Bhattacharya",
    image_url: "/Assets/faculty/raunak.jpg",
    webmail: "raunakbh@scai.iitd.ac.in",
    link: null,
    role: "faculty",
    year: null,
    department: "School of AI",
    department_category: "scai",
    office_contact: null,
    research_interest: null,
    focus: ["autonomous-systems", "reinforcement-learning", "robotics"],
  },
  {
    id: "22",
    name: "Prof. Sagar Sarkar",
    image_url: "/Assets/faculty/sagar.jpg",
    webmail: "sagar@mech.iitd.ac.in",
    link: "https://mech.iitd.ac.in/faculty-profile/197",
    role: "faculty",
    year: null,
    department: "Mechanical Engineering",
    department_category: "mechanical",
    office_contact: "+911126591131",
    research_interest: null,
    focus: ["additive-manufacturing", "laser-processing", "process-control", "ai", "manufacturing", "fatigue"],
  },
  {
    id: "23",
    name: "Prof. Shaurya Shriyam",
    image_url: "/Assets/faculty/shaurya.jpg",
    webmail: "shriyam@mech.iitd.ac.in",
    link: "https://mech.iitd.ac.in/faculty-profile/194",
    role: "faculty",
    year: null,
    department: "Mechanical Engineering",
    department_category: "mechanical",
    office_contact: "+911126598428",
    research_interest: null,
    focus: ["data-driven", "simulation", "robotics", "healthcare", "multi-agent", "planning", "reinforcement-learning", "networks"],
  },
  {
    id: "24",
    name: "Prof. Sumeet Agarwal",
    image_url: "/Assets/faculty/sumeet.png",
    webmail: "sumeet@iitd.ac.in",
    link: "https://web.iitd.ac.in/~sumeet/",
    role: "faculty",
    year: null,
    department: "School of AI",
    department_category: "scai",
    office_contact: "+911126596159",
    research_interest: null,
    focus: ["machine-learning", "networks", "cognitive-science", "computational-linguistics", "social-computing", "ai"],
  },
  {
    id: "25",
    name: "Prof. Vamsi Krishna Chalamalla",
    image_url: "/Assets/faculty/vamsi.jpg",
    webmail: "vchalama@mech.iitd.ac.in",
    link: "https://sites.google.com/site/vkchalama/",
    role: "faculty",
    year: null,
    department: "Applied Mechanics",
    department_category: "applied",
    office_contact: "+911126597976",
    research_interest: null,
    focus: ["fluid-mechanics", "cfd", "ocean-modeling", "turbulence", "computational-fluid-dynamics"],
  },
  {
    id: "26",
    name: "N. Parthasaradhi Reddy",
    image_url: "/Assets/batch_2026/parthasaradhi.jpg",
    webmail: "jrb242028@iitd.ac.in",
    link: "https://www.linkedin.com/in/parthasaradhi-reddy-n-2891011a8",
    role: "student",
    year: "2024-26",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "27",
    name: "Varun Vilas Shinde",
    image_url: "/Assets/batch_2026/varun.jpeg",
    webmail: "jrb242029@iitd.ac.in",
    link: "https://www.linkedin.com/in/varun-vilas-shinde",
    role: "student",
    year: "2024-26",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "28",
    name: "Nishant Govindrao Wankhade",
    image_url: "/Assets/batch_2026/nishant.jpeg",
    webmail: "jrb242030@iitd.ac.in",
    link: "https://www.linkedin.com/in/nishant-wankhade",
    role: "student",
    year: "2024-26",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "29",
    name: "Pawan Kumar",
    image_url: "/Assets/batch_2026/pawan.jpeg",
    webmail: "jrb242031@iitd.ac.in",
    link: "https://www.linkedin.com/in/p1608/",
    role: "student",
    year: "2024-26",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "30",
    name: "Savudam Sai Sathvik",
    image_url: "/Assets/batch_2026/sathvik.png",
    webmail: "jrb242022@iitd.ac.in",
    link: "https://www.linkedin.com/in/sai-sathvik-savudam-331535298/",
    role: "student",
    year: "2024-26",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "31",
    name: "Debangan Mandal",
    image_url: "/Assets/batch_2026/debangan.jpeg",
    webmail: "jrb242065@iitd.ac.in",
    link: "https://www.linkedin.com/in/debangan-mandal/",
    role: "student",
    year: "2024-26",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "32",
    name: "C Adithya",
    image_url: "/Assets/batch_2026/adithya.jpeg",
    webmail: "jrb242066@iitd.ac.in",
    link: "https://www.linkedin.com/in/adithya-c-8ab284217",
    role: "student",
    year: "2024-26",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "33",
    name: "Pratyay Das",
    image_url: "/Assets/batch_2026/pratyay.png",
    webmail: "jrb242033@iitd.ac.in",
    link: "https://www.linkedin.com/in/pratyaydas/",
    role: "student",
    year: "2024-26",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "34",
    name: "Adithya Krishna Vijay",
    image_url: "/Assets/new_students/adithya.jpeg",
    webmail: "jrb252019@bird.iitd.ac.in",
    link: "https://www.linkedin.com/in/adithya-krishna-969779351/",
    role: "student",
    year: "2025-27",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "35",
    name: "Mohd Zaid Chachiya",
    image_url: "/Assets/new_students/zaid.jpg",
    webmail: "jrb252020@bird.iitd.ac.in",
    link: "https://www.linkedin.com/in/mohammad-zaid-chachiya",
    role: "student",
    year: "2025-27",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "36",
    name: "Adarsh Pandey",
    image_url: "/Assets/new_students/adarsh.jpeg",
    webmail: "jrb252021@iitd.ac.in",
    link: "https://www.linkedin.com/in/adarsh-pandey0531",
    role: "student",
    year: "2025-27",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "37",
    name: "Gaurav Sharma",
    image_url: "/Assets/new_students/gaurav.jpg",
    webmail: "jrb252022@bird.iitd.ac.in",
    link: "https://www.linkedin.com/in/gauravsharma-13",
    role: "student",
    year: "2025-27",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "38",
    name: "Tarun Kumar",
    image_url: "/Assets/new_students/tarun.jpg",
    webmail: "jrb252023@bird.iitd.ac.in",
    link: "https://www.linkedin.com/in/tarun-kumar-a05532267",
    role: "student",
    year: "2025-27",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "39",
    name: "Vijayant Singh",
    image_url: "/Assets/new_students/vijayant.JPG",
    webmail: "jrb252024@iitd.ac.in",
    link: "https://www.linkedin.com/in/vijayant-singh",
    role: "student",
    year: "2025-27",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "40",
    name: "Pritosh Kumar",
    image_url: "/Assets/new_students/pritosh.jpg",
    webmail: "jrb252025@iitd.ac.in",
    link: null,
    role: "student",
    year: "2025-27",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "41",
    name: "Jivesh Kesar",
    image_url: "/Assets/new_students/jivesh.jpg",
    webmail: "jrb252026@iitd.ac.in",
    link: "https://www.linkedin.com/in/jivesh-kesar-a165531a2/",
    role: "student",
    year: "2025-27",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "42",
    name: "Harsh",
    image_url: "/Assets/new_students/harsh.jpeg",
    webmail: "jrb252049@iitd.ac.in",
    link: "https://www.linkedin.com/in/harsh-mulodhia/",
    role: "student",
    year: "2025-27",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "43",
    name: "Rohit Shankar Sinha",
    image_url: "/Assets/new_students/rohit.jpeg",
    webmail: "jrb252051@bird.iitd.ac.in",
    link: "https://www.linkedin.com/in/rohit-shankar-sinha-186887191",
    role: "student",
    year: "2025-27",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "44",
    name: "Utkarsh Joshi",
    image_url: "/Assets/new_students/utkarsh.jpeg",
    webmail: "jrb252052@iitd.ac.in",
    link: "https://www.linkedin.com/in/utkarsh-joshi-16090b234",
    role: "student",
    year: "2025-27",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "45",
    name: "Uthith Naraayanan",
    image_url: "/Assets/new_students/uthith.jpg",
    webmail: "jrb252054@iitd.ac.in",
    link: "https://www.linkedin.com/in/uthith-naraayanan-g-54a4b9293",
    role: "student",
    year: "2025-27",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "46",
    name: "Varnita Verma",
    image_url: "/Assets/post-docs/varnita.png",
    webmail: "varnitaverma2@gmail.com",
    link: null,
    role: "postdoc",
    year: "Post-Doc (2023–2025)",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "47",
    name: "Sarvesh Khire",
    image_url: "/Assets/students/Sarvesh Khire.png",
    webmail: "jrb232679@iitd.ac.in",
    link: null,
    role: "alumni",
    year: "M.Tech Robotics (2023–2025)",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "48",
    name: "Devang Sharma",
    image_url: "/Assets/students/Devang Sharma.png",
    webmail: "jrb232683@iitd.ac.in",
    link: null,
    role: "alumni",
    year: "M.Tech Robotics (2023–2025)",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "49",
    name: "Vaibhav Kathait",
    image_url: "/Assets/students/Vaibhav Kathait.png",
    webmail: "jrb232680@iitd.ac.in",
    link: null,
    role: "alumni",
    year: "M.Tech Robotics (2023–2025)",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "50",
    name: "Rutvik Patel",
    image_url: "/Assets/students/Rutvik Patel.png",
    webmail: "jrb232682@iitd.ac.in",
    link: null,
    role: "alumni",
    year: "M.Tech Robotics (2023–2025)",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "51",
    name: "Gaurang Patil",
    image_url: "/Assets/students/Gaurang Patil.png",
    webmail: "jrb232671@iitd.ac.in",
    link: null,
    role: "alumni",
    year: "M.Tech Robotics (2023–2025)",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "52",
    name: "Umesh Gupta",
    image_url: "/Assets/students/Umesh Gupta.png",
    webmail: "jrb232678@iitd.ac.in",
    link: null,
    role: "alumni",
    year: "M.Tech Robotics (2023–2025)",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "53",
    name: "Rishabh Vajpayee",
    image_url: "/Assets/students/Rishabh Vajpayee.png",
    webmail: "jrb232677@iitd.ac.in",
    link: null,
    role: "alumni",
    year: "M.Tech Robotics (2023–2025)",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "54",
    name: "Hemant Kumar Singh",
    image_url: "/Assets/students/Hemant Kumar Singh.png",
    webmail: "jrb232676@iitd.ac.in",
    link: null,
    role: "alumni",
    year: "M.Tech Robotics (2023–2025)",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
  {
    id: "55",
    name: "Lalit Saraf",
    image_url: "/Assets/students/Lalit Saraf.png",
    webmail: "jrb232684@iitd.ac.in",
    link: null,
    role: "alumni",
    year: "M.Tech Robotics (2023–2025)",
    department: null,
    department_category: null,
    office_contact: null,
    research_interest: null,
    focus: [],
  },
];